name: Generate and Deploy Doxygen

on:
  push:
    branches: [ inkt/MapGeneration ]  # Or your default branch name
  workflow_dispatch:    # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen Documentation
        run: |
          doxygen Doxyfile
          # Fix file permissions
          chmod -R 755 ./docs/html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/html  # The folder the action should deploy
          branch: gh-pages   # The branch the action should deploy to